"""Add user_id foreign key to Driver model

Revision ID: fbd1cabbdf85
Revises: 
Create Date: 2026-02-08 15:42:08.364879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbd1cabbdf85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vehicle_assignments_id', table_name='vehicle_assignments')
    op.drop_table('vehicle_assignments')
    op.drop_index('ix_permissions_id', table_name='permissions')
    op.drop_table('permissions')
    op.drop_index('ix_renting_contracts_id', table_name='renting_contracts')
    op.drop_table('renting_contracts')
    op.drop_index('ix_reservations_id', table_name='reservations')
    op.drop_table('reservations')
    op.drop_index('ix_fines_id', table_name='fines')
    op.drop_table('fines')
    op.drop_index('ix_itv_records_id', table_name='itv_records')
    op.drop_table('itv_records')
    op.drop_index('ix_maintenance_records_id', table_name='maintenance_records')
    op.drop_table('maintenance_records')
    op.drop_index('ix_vehicle_taxes_id', table_name='vehicle_taxes')
    op.drop_table('vehicle_taxes')
    op.drop_index('ix_vehicle_insurances_id', table_name='vehicle_insurances')
    op.drop_table('vehicle_insurances')
    op.drop_index('ix_vehicle_pickups_id', table_name='vehicle_pickups')
    op.drop_table('vehicle_pickups')
    op.drop_index('ix_accidents_id', table_name='accidents')
    op.drop_table('accidents')
    op.drop_index('ix_drivers_document_number', table_name='drivers')
    op.drop_index('ix_drivers_id', table_name='drivers')
    op.drop_table('drivers')
    op.drop_index('ix_vehicles_id', table_name='vehicles')
    op.drop_index('ix_vehicles_license_plate', table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_organization_units_id', table_name='organization_units')
    op.drop_table('organization_units')
    op.drop_index('ix_urban_access_authorizations_id', table_name='urban_access_authorizations')
    op.drop_table('urban_access_authorizations')
    op.drop_table('role_permissions')
    op.drop_index('ix_providers_id', table_name='providers')
    op.drop_table('providers')
    op.drop_index('ix_vehicle_driver_associations_id', table_name='vehicle_driver_associations')
    op.drop_table('vehicle_driver_associations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_driver_associations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), nullable=False),
    sa.Column('driver_id', sa.INTEGER(), nullable=False),
    sa.Column('start_date', sa.DATETIME(), nullable=False),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vehicle_driver_associations_id', 'vehicle_driver_associations', ['id'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('provider_type', sa.VARCHAR(length=11), nullable=False),
    sa.Column('contact_person', sa.VARCHAR(length=100), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('website', sa.VARCHAR(length=200), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_providers_id', 'providers', ['id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), nullable=False),
    sa.Column('permission_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('urban_access_authorizations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), nullable=False),
    sa.Column('authorization_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('issuing_authority', sa.VARCHAR(length=100), nullable=False),
    sa.Column('authorization_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('zone_description', sa.VARCHAR(length=200), nullable=True),
    sa.Column('start_date', sa.DATETIME(), nullable=False),
    sa.Column('end_date', sa.DATETIME(), nullable=False),
    sa.Column('conditions', sa.TEXT(), nullable=True),
    sa.Column('document_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('alert_days_before_expiry', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authorization_number')
    )
    op.create_index('ix_urban_access_authorizations_id', 'urban_access_authorizations', ['id'], unique=False)
    op.create_table('organization_units',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.Column('manager_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('contact_email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('contact_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_organization_units_id', 'organization_units', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('role', sa.VARCHAR(length=18), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('license_plate', sa.VARCHAR(length=20), nullable=False),
    sa.Column('make', sa.VARCHAR(length=50), nullable=False),
    sa.Column('model', sa.VARCHAR(length=50), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('color', sa.VARCHAR(length=30), nullable=True),
    sa.Column('vin', sa.VARCHAR(length=17), nullable=True),
    sa.Column('vehicle_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('status', sa.VARCHAR(length=14), nullable=True),
    sa.Column('ownership_type', sa.VARCHAR(length=7), nullable=False),
    sa.Column('organization_unit_id', sa.INTEGER(), nullable=True),
    sa.Column('current_mileage', sa.INTEGER(), nullable=True),
    sa.Column('fuel_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('fuel_capacity', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['organization_unit_id'], ['organization_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vin')
    )
    op.create_index('ix_vehicles_license_plate', 'vehicles', ['license_plate'], unique=False)
    op.create_index('ix_vehicles_id', 'vehicles', ['id'], unique=False)
    op.create_table('drivers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('document_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('document_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('driver_license_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('driver_license_expiry', sa.DATETIME(), nullable=False),
    sa.Column('driver_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('organization_unit_id', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_unit_id'], ['organization_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_license_number'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_drivers_id', 'drivers', ['id'], unique=False)
    op.create_index('ix_drivers_document_number', 'drivers', ['document_number'], unique=False)
    op.create_table('accidents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), nullable=False),
    sa.Column('driver_id', sa.INTEGER(), nullable=True),
    sa.Column('accident_date', sa.DATETIME(), nullable=False),
    sa.Column('location', sa.VARCHAR(length=200), nullable=False),
    sa.Column('severity', sa.VARCHAR(length=8), nullable=False),
    sa.Column('status', sa.VARCHAR(length=15), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('weather_conditions', sa.VARCHAR(length=100), nullable=True),
    sa.Column('road_conditions', sa.VARCHAR(length=100), nullable=True),
    sa.Column('other_parties_involved', sa.TEXT(), nullable=True),
    sa.Column('witnesses', sa.TEXT(), nullable=True),
    sa.Column('police_report_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('insurance_claim_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('damage_description', sa.TEXT(), nullable=True),
    sa.Column('estimated_repair_cost', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('actual_repair_cost', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('repair_provider', sa.VARCHAR(length=100), nullable=True),
    sa.Column('repair_start_date', sa.DATETIME(), nullable=True),
    sa.Column('repair_completion_date', sa.DATETIME(), nullable=True),
    sa.Column('responsible_party', sa.VARCHAR(length=100), nullable=True),
    sa.Column('document_paths', sa.TEXT(), nullable=True),
    sa.Column('photos_paths', sa.TEXT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_accidents_id', 'accidents', ['id'], unique=False)
    op.create_table('vehicle_pickups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reservation_id', sa.INTEGER(), nullable=False),
    sa.Column('driver_id', sa.INTEGER(), nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), nullable=False),
    sa.Column('pickup_status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('pickup_time', sa.DATETIME(), nullable=True),
    sa.Column('return_time', sa.DATETIME(), nullable=True),
    sa.Column('start_mileage', sa.INTEGER(), nullable=True),
    sa.Column('end_mileage', sa.INTEGER(), nullable=True),
    sa.Column('fuel_level_start', sa.INTEGER(), nullable=True),
    sa.Column('fuel_level_end', sa.INTEGER(), nullable=True),
    sa.Column('vehicle_condition_start', sa.TEXT(), nullable=True),
    sa.Column('vehicle_condition_end', sa.TEXT(), nullable=True),
    sa.Column('not_taken_reason', sa.TEXT(), nullable=True),
    sa.Column('not_taken_attachment', sa.VARCHAR(length=500), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reservation_id')
    )
    op.create_index('ix_vehicle_pickups_id', 'vehicle_pickups', ['id'], unique=False)
    op.create_table('vehicle_insurances',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), nullable=False),
    sa.Column('insurance_type', sa.VARCHAR(length=21), nullable=False),
    sa.Column('insurance_company', sa.VARCHAR(length=100), nullable=False),
    sa.Column('policy_number', sa.VARCHAR(length=100), nullable=False),
    sa.Column('premium_amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('start_date', sa.DATETIME(), nullable=False),
    sa.Column('end_date', sa.DATETIME(), nullable=False),
    sa.Column('payment_date', sa.DATETIME(), nullable=True),
    sa.Column('payment_status', sa.VARCHAR(length=9), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('payment_reference', sa.VARCHAR(length=100), nullable=True),
    sa.Column('document_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('coverage_details', sa.TEXT(), nullable=True),
    sa.Column('alert_days_before', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_number')
    )
    op.create_index('ix_vehicle_insurances_id', 'vehicle_insurances', ['id'], unique=False)
    op.create_table('vehicle_taxes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), nullable=False),
    sa.Column('tax_type', sa.VARCHAR(length=5), nullable=False),
    sa.Column('tax_year', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('due_date', sa.DATETIME(), nullable=False),
    sa.Column('payment_date', sa.DATETIME(), nullable=True),
    sa.Column('payment_status', sa.VARCHAR(length=8), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('payment_reference', sa.VARCHAR(length=100), nullable=True),
    sa.Column('document_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('alert_days_before', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vehicle_taxes_id', 'vehicle_taxes', ['id'], unique=False)
    op.create_table('maintenance_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), nullable=False),
    sa.Column('maintenance_type', sa.VARCHAR(length=18), nullable=False),
    sa.Column('status', sa.VARCHAR(length=11), nullable=True),
    sa.Column('scheduled_date', sa.DATETIME(), nullable=False),
    sa.Column('completed_date', sa.DATETIME(), nullable=True),
    sa.Column('mileage_at_service', sa.INTEGER(), nullable=True),
    sa.Column('cost', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('provider_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('provider_contact', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('work_performed', sa.TEXT(), nullable=True),
    sa.Column('parts_replaced', sa.TEXT(), nullable=True),
    sa.Column('next_service_date', sa.DATETIME(), nullable=True),
    sa.Column('next_service_mileage', sa.INTEGER(), nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('document_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('provider_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_maintenance_records_id', 'maintenance_records', ['id'], unique=False)
    op.create_table('itv_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), nullable=False),
    sa.Column('inspection_date', sa.DATETIME(), nullable=False),
    sa.Column('expiry_date', sa.DATETIME(), nullable=False),
    sa.Column('next_inspection_date', sa.DATETIME(), nullable=True),
    sa.Column('result', sa.VARCHAR(length=12), nullable=False),
    sa.Column('status', sa.VARCHAR(length=7), nullable=True),
    sa.Column('inspection_center', sa.VARCHAR(length=200), nullable=True),
    sa.Column('inspector_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('certificate_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('defects_found', sa.TEXT(), nullable=True),
    sa.Column('defects_severity', sa.VARCHAR(length=50), nullable=True),
    sa.Column('cost', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('mileage_at_inspection', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_number')
    )
    op.create_index('ix_itv_records_id', 'itv_records', ['id'], unique=False)
    op.create_table('fines',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), nullable=False),
    sa.Column('driver_id', sa.INTEGER(), nullable=True),
    sa.Column('fine_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('fine_type', sa.VARCHAR(length=13), nullable=False),
    sa.Column('fine_date', sa.DATETIME(), nullable=False),
    sa.Column('notification_date', sa.DATETIME(), nullable=True),
    sa.Column('location', sa.VARCHAR(length=200), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('reduced_amount', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('payment_deadline', sa.DATETIME(), nullable=True),
    sa.Column('reduced_payment_deadline', sa.DATETIME(), nullable=True),
    sa.Column('payment_date', sa.DATETIME(), nullable=True),
    sa.Column('payment_amount', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.VARCHAR(length=9), nullable=True),
    sa.Column('responsible_driver', sa.VARCHAR(length=100), nullable=True),
    sa.Column('appeal_filed', sa.BOOLEAN(), nullable=True),
    sa.Column('appeal_date', sa.DATETIME(), nullable=True),
    sa.Column('appeal_reason', sa.TEXT(), nullable=True),
    sa.Column('appeal_result', sa.VARCHAR(length=100), nullable=True),
    sa.Column('document_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('payment_receipt_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fine_number')
    )
    op.create_index('ix_fines_id', 'fines', ['id'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), nullable=False),
    sa.Column('driver_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('start_date', sa.DATETIME(), nullable=False),
    sa.Column('end_date', sa.DATETIME(), nullable=False),
    sa.Column('actual_start_date', sa.DATETIME(), nullable=True),
    sa.Column('actual_end_date', sa.DATETIME(), nullable=True),
    sa.Column('actual_start_mileage', sa.INTEGER(), nullable=True),
    sa.Column('actual_end_mileage', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=11), nullable=True),
    sa.Column('purpose', sa.TEXT(), nullable=False),
    sa.Column('destination', sa.VARCHAR(length=200), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('cancellation_reason', sa.TEXT(), nullable=True),
    sa.Column('cancelled_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('organization_unit_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reservations_id', 'reservations', ['id'], unique=False)
    op.create_table('renting_contracts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('contract_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('start_date', sa.DATETIME(), nullable=False),
    sa.Column('end_date', sa.DATETIME(), nullable=False),
    sa.Column('monthly_cost', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('total_cost', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('km_limit', sa.INTEGER(), nullable=True),
    sa.Column('excess_km_cost', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('contact_person', sa.VARCHAR(length=100), nullable=True),
    sa.Column('contact_email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('contact_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('terms_and_conditions', sa.TEXT(), nullable=True),
    sa.Column('document_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('alert_days_before_expiry', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_number')
    )
    op.create_index('ix_renting_contracts_id', 'renting_contracts', ['id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_permissions_id', 'permissions', ['id'], unique=False)
    op.create_table('vehicle_assignments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), nullable=False),
    sa.Column('driver_id', sa.INTEGER(), nullable=False),
    sa.Column('organization_unit_id', sa.INTEGER(), nullable=False),
    sa.Column('assignment_type', sa.VARCHAR(length=13), nullable=False),
    sa.Column('start_date', sa.DATETIME(), nullable=False),
    sa.Column('end_date', sa.DATETIME(), nullable=False),
    sa.Column('assignment_fee', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.VARCHAR(length=8), nullable=True),
    sa.Column('payment_date', sa.DATETIME(), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('payment_reference', sa.VARCHAR(length=100), nullable=True),
    sa.Column('document_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('purpose', sa.TEXT(), nullable=False),
    sa.Column('destination', sa.VARCHAR(length=200), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['organization_unit_id'], ['organization_units.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vehicle_assignments_id', 'vehicle_assignments', ['id'], unique=False)
    # ### end Alembic commands ###
